apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: quarkus-mar3-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-mar3-3
  name: quarkus-mar3-3
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: quarkus-mar3-3
